[[news]]
date = "2026-03"
content = "One paper has been submitted to ACM MM 2026 🎓"

[[news]]
date = "2025-02"
content = "Started new research project on Aerial Multiview Spatio-temporal Reasoning"

[[news]]
date = "2026-02"
content = "One paper has been accepted by Acta Aeronautica et Astronautica Sinica 🎓"

[[news]]
date = "2026-02"
content = "One paper has been accepted by CVPR 2026 Findings 🎓"

[[news]]
date = "2025-11"
content = "One paper has been accepted by AAAI 2026 🎓"

[[news]]
date = "2025-08"
content = "One paper has been accepted by ICAUS 2025 🎓"

[[news]]
date = "2025-02"
content = "Started new research project on Zero-shot UAV Vision-and-Language Navigation"

[[news]]
date = "2024-11"
content = "Started new research project on Fine-grained Action Recognition"

[[news]]
date = "2024-11"
content = "Attended COP29 as NPU Student Representative in Baku, Azerbaijan 🌍"

[[news]]
date = "2024-11"
content = "Won Second Prize in Challenge Cup 2024 🏆"

[[news]]
date = "2024-08"
content = "Completed internship at QingCloud Technology as AI Development Engineer"
